# Generated by Django 5.2 on 2026-02-25 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-solid fa-arrow-up', max_length=50)),
                ('color', models.CharField(default='#27ae60', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de promotion',
                'verbose_name_plural': 'Types de promotion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('levels', models.JSONField(default=list, help_text='Liste des niveaux de carrière')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'verbose_name': 'Chemin de carrière',
                'verbose_name_plural': 'Chemins de carrière',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position', models.CharField(max_length=100)),
                ('old_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_grade', models.CharField(blank=True, max_length=50)),
                ('new_position', models.CharField(max_length=100)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_grade', models.CharField(blank=True, max_length=50)),
                ('promotion_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('reason', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('salary_increase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_increase_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('implemented', 'Implémenté'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='promotions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employees.employee')),
                ('new_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_promotions', to='departments.department')),
                ('old_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_promotions', to='departments.department')),
                ('promotion_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotions.promotiontype')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-promotion_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='promotions.promotion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de promotion',
                'verbose_name_plural': 'Historiques de promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['employee', 'status'], name='promotions__employe_368ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['promotion_date'], name='promotions__promoti_5a1533_idx'),
        ),
    ]
