# Generated by Django 5.2.12 on 2026-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='hour_rate',
            new_name='base_salary',
        ),
        migrations.RenameField(
            model_name='promotion',
            old_name='position',
            new_name='name',
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
