# Generated by Django 5.2.12 on 2026-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_created_at_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-hire_date']},
        ),
    ]
