# Generated by Django 5.2.12 on 2026-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='final_salary',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_deductions',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
