# Generated by Django 5.2.12 on 2026-03-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_alter_salary_final_salary_alter_salary_total_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='total_hours',
        ),
    ]
