# Generated by Django 5.2 on 2026-03-02 00:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mon Entreprise', max_length=200)),
                ('check_in_start', models.TimeField(default='08:00')),
                ('check_in_end', models.TimeField(default='09:30')),
                ('check_out_start', models.TimeField(default='16:30')),
                ('check_out_end', models.TimeField(default='19:00')),
                ('work_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('enable_geolocation', models.BooleanField(default=False)),
                ('enable_photo', models.BooleanField(default=False)),
                ('late_threshold_minutes', models.IntegerField(default=15, help_text='Minutes de tolérance pour les retards')),
                ('auto_absent_after', models.TimeField(default='10:00', help_text="Heure à partir de laquelle l'absence est automatique")),
            ],
            options={
                'verbose_name': 'Paramètre de pointage',
                'verbose_name_plural': 'Paramètres de pointage',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_photo', models.ImageField(blank=True, null=True, upload_to='attendance/check_in/')),
                ('check_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance/check_out/')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures travaillées')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures supplémentaires')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En retard'), ('HALF_DAY', 'Demi-journée'), ('MISSION', 'En mission'), ('REMOTE', 'Télétravail'), ('HOLIDAY', 'Congé')], default='PRESENT', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
